### ISSUE TITLE
Falta de Tempo

### ISSUE THREAD

**Issue by ottok92** [Arkhrer/twitter-mental-health-mining#1]
Jonas,
foi mal, cara. Estou muito corrido essa semana, então acabei não fazendo os resumos.
Pelo menos, parece que ele não está tirando ponto para entrega fora do prazo.
Vamos fazendo nesse feriado. Vou te mantendo atualizado.

**Comment by Arkhrer** [comment]
Oi Otto, como não tive mais nenhum feedback seu acabei terminando a tarefa hoje,  não esqueça de enviála pelo moodle. Me avise se for fazer alguma alteração para eu reenviar a minha também

**Comment by ottok92** [comment]
Mandou muito, Jonas! Só vi sua mensagem agora. Vou enviar logo pra ver se ele não desconta ponto.
Valeu por me cobrir nessa. Fico te devendo essa. Até amanhã, cara.
